# Generated by Django 5.0.7 on 2024-08-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisement_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='draft',
            field=models.TextField(default=''),
        ),
    ]
