# Generated by Django 5.0.7 on 2024-08-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_alter_advertisement_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='draft',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='favorite',
            field=models.BooleanField(default=''),
        ),
    ]
