# Generated by Django 5.0.7 on 2024-08-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_alter_advertisement_draft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='draft',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.TextField(choices=[('OPEN', 'Открыто'), ('CLOSED', 'Закрыто'), ('DRAFT', 'Черновик')], default='OPEN'),
        ),
    ]
